name: Build
on:
  push:
    branches: [ test ]
    tags:
      - '*'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          COMMIT=`(printf "commit %s\0" $(git cat-file commit HEAD | wc -c); git cat-file commit HEAD) | sha1sum | cut -c1-8`
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV

      - name: Build
        uses: kingyond/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: oaf
          CUSTOM_PKG_DIR: oaf
          CUSTOM_SRC_DIR: oaf

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: |
            bin/packages/${{ matrix.arch }}/base/oaf*.ipk

      - name: Deploy Files To Release (Tag)
        uses: ncipollo/release-action@v1.8.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: bin/packages/${{ matrix.arch }}/base/oaf*.ipk

      - name: Deploy Files To Release (Commit)
        uses: ncipollo/release-action@v1.8.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.COMMIT }}
          artifacts: bin/packages/${{ matrix.arch }}/base/oaf*.ipk
